Adds aws elb support as embedded jars; doesn't work though.
Need to add brooklyn.*  to the WHITELIST.  Let's change that class to io.cloudsoft.aws.elb..

Test with

location: amazon-eu-west-1
name: elb-test
services:
- type: brooklyn.entity.proxy.aws.ElbController
  name: ELB
  brooklyn.config:
    aws.elb.loadBalancerName: br-example-1
    aws.elb.loadBalancerProtocol: HTTP
    aws.elb.instancePort: 8080
    loadbalancer.serverpool: $brooklyn:entity("cluster")

- type: org.apache.brooklyn.entity.group.DynamicCluster
  id: cluster
  name: cluster
  brooklyn.config:
    initialSize: 2
    memberSpec:
      $brooklyn:entitySpec:
        type: http-server

Failed to start ELB controller with

Failed after 209ms: Invalid java type: Could not initialize class com.amazonaws.http.conn.$Proxy89

java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.http.conn.$Proxy89
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory.wrap(ClientConnectionManagerFactory.java:52)
	at com.amazonaws.http.impl.client.SdkHttpClient.<init>(SdkHttpClient.java:29)
	at com.amazonaws.http.HttpClientFactory.createHttpClient(HttpClientFactory.java:116)
	at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:217)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:136)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:120)
	at com.amazonaws.services.elasticloadbalancing.AmazonElasticLoadBalancingClient.<init>(AmazonElasticLoadBalancingClient.java:176)
	at com.amazonaws.services.elasticloadbalancing.AmazonElasticLoadBalancingClient.<init>(AmazonElasticLoadBalancingClient.java:153)
	at brooklyn.entity.proxy.aws.ElbControllerImpl.newClient(ElbControllerImpl.java:628)
	at brooklyn.entity.proxy.aws.ElbControllerImpl.doesLoadBalancerExist(ElbControllerImpl.java:565)
	at brooklyn.entity.proxy.aws.ElbControllerImpl.startLoadBalancer(ElbControllerImpl.java:320)
	at brooklyn.entity.proxy.aws.ElbControllerImpl.doStart(ElbControllerImpl.java:123)
	at org.apache.brooklyn.entity.proxy.AbstractNonProvisionedControllerImpl.start(AbstractNonProvisionedControllerImpl.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:149)
	at groovy.lang.MetaObjectProtocol$invokeMethod.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at groovy.lang.MetaObjectProtocol$invokeMethod.call(Unknown Source)
	at org.apache.brooklyn.util.groovy.GroovyJavaMethods.invokeMethodOnMetaClass(GroovyJavaMethods.java:191)
	at org.apache.brooklyn.core.mgmt.internal.AbstractManagementContext.invokeEffectorMethodLocal(AbstractManagementContext.java:319)
	at org.apache.brooklyn.core.mgmt.internal.AbstractManagementContext.invokeEffectorMethodSync(AbstractManagementContext.java:343)
	at org.apache.brooklyn.core.mgmt.internal.EffectorUtils.invokeMethodEffector(EffectorUtils.java:276)
	at org.apache.brooklyn.core.effector.MethodEffector.call(MethodEffector.java:148)
	at org.apache.brooklyn.core.entity.trait.Startable$StartEffectorBody.call(Startable.java:56)
	at org.apache.brooklyn.core.entity.trait.Startable$StartEffectorBody.call(Startable.java:50)
	at org.apache.brooklyn.core.effector.EffectorTasks$EffectorBodyTaskFactory$1.call(EffectorTasks.java:82)
	at org.apache.brooklyn.util.core.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:359)
	at org.apache.brooklyn.util.core.task.BasicExecutionManager$SubmissionCallable.call(BasicExecutionManager.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)